# Generated by Django 4.2.5 on 2023-09-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_remove_event_geek_remove_event_teachers_and_more'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('dateRegistered', models.DateTimeField()),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
