# Generated by Django 4.2.5 on 2023-09-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_remove_teacher_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geek',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Attends',
        ),
    ]
